### ISSUE TITLE
When the chunk within the Hyperbox is not loaded MA seeds completely stop growing and break

### ISSUE THREAD

**Issue by Minaayaa** [Commoble/hyperbox#23]
So I am playing the modpack AlltheMods9 (on a server) and I wanted to set up an automated Cropfarm with Mystical Agriculture inside of Hyperboxes.
Now after a lot of time setting all of my hyperboxes up and doing my last trip through all of them i realized, that none of the seeds are growing anymore. After a little testing it turns out, if you give a blockupdate to one of those Crops, all connected seeds (due to other blockupdates next to them) break. 

The only real way to bypass this behavior is by permanently chunkloading the chunk within the hyperbox, but only if it was loaded before leaving the hyperbox after having planetd the seeds

**Comment by Minaayaa** [comment]
Also i dont know if this is related to the issue but the server keeps spamming this error:
[IO-Worker-45/ERROR] [minecraft/IOWorker]: Failed to store chunk [0, 0]
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?] {}
        at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?] {}
        at net.minecraft.nbt.CompoundTag.m_6434_(CompoundTag.java:133) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.nbt_memory_usage.CompoundTagMixin,pl:mixin:A}
        at net.minecraft.nbt.NbtIo.m_128950_(NbtIo.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading}
        at net.minecraft.nbt.NbtIo.m_128941_(NbtIo.java:108) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.m_63708_(RegionFileStorage.java:79) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at commoble.hyperbox.dimension.HyperboxRegionFileStorage.m_63708_(HyperboxRegionFileStorage.java:26) ~[hyperbox-1.20.1-4.0.1.0.jar%23673!/:4.0.1.0] {re:classloading}
        at net.minecraft.world.level.chunk.storage.IOWorker.m_63535_(IOWorker.java:260) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:hyperbox.mixins.json:IOWorkerMixin,pl:mixin:APP:railways-common.mixins.json:MixinIOWorker,pl:mixin:A}
        at net.minecraft.world.level.chunk.storage.IOWorker.m_63553_(IOWorker.java:250) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:hyperbox.mixins.json:IOWorkerMixin,pl:mixin:APP:railways-common.mixins.json:MixinIOWorker,pl:mixin:A}
        at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:60) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] {}
        at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}

**Comment by Minaayaa** [comment]
Ok i have figured out what the problem with the seeds was. Like a nother user already discribed, if the hyperbox is chunkloaded or in my case it didnt even matter wether it was chunkloaded, the lighting breaks and is reduced to only the soucre block itself (in my case glowstone), which causes crop growth to stop and if the seeds get a block update to break. The confusing part ist, that it doesnt happen in every hyperbox, but i dont know whats different between them yet.
