### ISSUE TITLE
Crash with valkyrien skies (1.20.1)

### ISSUE THREAD

**Issue by MarkinSCode** [Commoble/hyperbox#25]
The game instantly crashes when trying to load the hyperbox dimension.

mods:
valkyrienskies-120-2.3.0-beta.5
eureka-1201-1.5.1-beta.3
kotlinforforge-4.11.0-all
hyperbox-1.20.1-4.0.2.0

crashlog:
Description: Exception in server tick loop

org.valkyrienskies.core.impl.util.assertions.stages.ConstraintFailedException: Constraints failed. Stages since last reset: [PRE_TICK, GET_LAST_TICK_CHANGES, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, GET_CURRENT_TICK_CHANGES, CLEAR_FOR_RESET, UPDATE_PLAYERS, UPDATE_DIMENSIONS]
Required stages matching predicate in the following order: [PRE_TICK, oneOf[UPDATE_DIMENSIONS, UPDATE_BLOCKS, UPDATE_CHUNKS], POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, CLEAR_FOR_RESET, UPDATE_PLAYERS]
	at org.valkyrienskies.core.impl.util.assertions.stages.TickStageEnforcerImpl.stage(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23163!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.game.ships.ShipObjectServerWorld.removeDimension(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23163!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.handler$zbp000$preTick(MinecraftServer.java:2006) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by FranFkntastic** [comment]
Also experiencing this.

**Comment by 3th3** [comment]
I concur.

**Comment by CraftyZombie** [comment]
Replicated with the following stats:
Forge: 47.3.33
Minecraft: 1.20.1
Mods:
- Valkyrien Skies 2.3.0-beta.5
- Hyperbox 4.0.2.0
- Kotlin for Forge 4.11.0

These are my logs, including latest.log, debug.log, and the crash report:
https://gist.github.com/CraftyZombie/cf8ba4769986aba4c60231b255689d3b
