### ISSUE TITLE
game crash when a hyperbox is entered for the first time

### ISSUE THREAD

**Issue by ouravantgarde** [Commoble/hyperbox#4]
when you place a new hyperbox and enter it, it crashes the game. everything is fine afterwards and its still useable just annoying. i have DREAMT of a mod like this and will do literally anything to help fix this crash

**Comment by Commoble** [comment]
I'm unable to reproduce any crashes, can you pastebin the crash log?

**Comment by ouravantgarde** [comment]
`Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$17675/551044335.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Missing Dimension ResourceKey[minecraft:dimension / hyperbox:generated_hyperbox/502236bb-2949-490c-9fa4-5e88df7b3357]
	at com.qouteall.immersive_portals.dimension_sync.DimensionIdRecord.getIntId(DimensionIdRecord.java:39)
	at com.qouteall.immersive_portals.dimension_sync.DimId.writeWorldId(DimId.java:24)
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.encode(StcRedirected.java:59)
	at com.qouteall.hiding_in_the_bushes.network.NetworkMain$$Lambda$14418/1601365206.accept(Unknown Source)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:134)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$19354/829426955.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:132)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:147)
	at net.minecraftforge.fml.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:85)
	at net.minecraftforge.fml.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:98)
	at net.minecraftforge.fml.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:129)
	at com.qouteall.hiding_in_the_bushes.MyNetwork.createRedirectedMessage(MyNetwork.java:47)
	at net.minecraft.server.management.PlayerList.handler$bgi000$sendToDimension(PlayerList.java:2464)
	at net.minecraft.server.management.PlayerList.func_232642_a_(PlayerList.java)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:293)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	... 6 more`

**Comment by Commoble** [comment]
Might be a problem with Immersive Portals, it looks like they're not currently able to handle dimensions being unloaded.

They may or may not be able to prevent this crash on their end, otherwise it might not be fixable until forge gets a standard API for handling dynamic dimensions again
