### ISSUE TITLE
Crash whenever I enter an hyperbox

### ISSUE THREAD

**Issue by GatoLeyo** [Commoble/hyperbox#8]
Whenever I reload the world I'm inside the hyperbox but everything is black and I'm unable to place blocks (tho I can move and seems like the bedrock is still there somehow since I haven't fell into the void), the only way out is /kill

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/31/22, 12:01 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.m_122424_()" because "side" is null
	at commoble.hyperbox.blocks.ApertureBlockEntity.getCapability(ApertureBlockEntity.java:62) ~[hyperbox-1.18.1-2.0.0.0.jar%2370!/:2.0.0.0] {re:classloading}
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:34) ~[forge-1.18.1-39.1.1-universal.jar%2396!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.handler$zdm000$sendBlockEntityCaps(ClientboundLevelChunkPacketData.java:543) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1459) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:hyperbox.mixins.json:ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:1009) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:hyperbox.mixins.json:ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:1195) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:hyperbox.mixins.json:ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1360) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:hyperbox.mixins.json:ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:458) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1559) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1542) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:137) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:98) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:76) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:834) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8622_(ServerLevel.java:763) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_8999_(ServerPlayer.java:1393) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at commoble.hyperbox.dimension.TeleportHelper.sendPlayerToDimension(TeleportHelper.java:19) ~[hyperbox-1.18.1-2.0.0.0.jar%2370!/:2.0.0.0] {re:classloading}
	at commoble.hyperbox.dimension.DelayedTeleportData.tick(DelayedTeleportData.java:71) ~[hyperbox-1.18.1-2.0.0.0.jar%2370!/:2.0.0.0] {re:classloading}
	at commoble.hyperbox.Hyperbox.onPostServerWorldTick(Hyperbox.java:214) ~[hyperbox-1.18.1-2.0.0.0.jar%2370!/:2.0.0.0] {re:classloading}
	at commoble.hyperbox.Hyperbox.onHighPriorityWorldTick(Hyperbox.java:184) ~[hyperbox-1.18.1-2.0.0.0.jar%2370!/:2.0.0.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreWorldTick(ForgeEventFactory.java:853) ~[forge-1.18.1-39.1.1-universal.jar%2396!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:865) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2392!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 6155646648 bytes (5870 MiB) / 9663676416 bytes (9216 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 3072.00
	Graphics card #0 deviceId: 0x1c02
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 20175.70
	Virtual memory used (MB): 16297.39
	Swap memory total (MB): 3840.54
	Swap memory used (MB): 193.47
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Gatoleyo'/78, l='ServerLevel[Test]', x=263.50, y=1.50, z=269.50]]
	Data Packs: vanilla, mod:tconstruct (incompatible), mod:rsrequestify (incompatible), mod:farmersdelight, mod:hostilenetworks (incompatible), mod:immersiveengineering, mod:easymagic, mod:jei, mod:wthit, mod:flywheel, mod:alloyed (incompatible), mod:curios, mod:mantle (incompatible), mod:create, mod:placebo (incompatible), mod:storagedrawers (incompatible), mod:toughasnails (incompatible), mod:chromatocreeper (incompatible), mod:betterthirdperson, mod:sophisticatedbackpacks (incompatible), mod:buddycardsexp, mod:ore_creeper (incompatible), mod:clickmachine (incompatible), mod:puzzleslib, mod:hyperbox (incompatible), mod:pizzacraft (incompatible), mod:randomium (incompatible), mod:mininggadgets (incompatible), mod:forge, mod:infiniverse, mod:easyshulkerboxes, mod:buddycards, mod:refinedstorage, mod:refinedstorageaddons, mod:tradingpost, mod:selene (incompatible), mod:supplementaries (incompatible), mod:dungeons_arise, mod:createaddition (incompatible), mod:aquaculture (incompatible), Supplementaries Virtual Resourcepack
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.1_HD_U_H6
	OptiFine Build: 20220324-210209
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 496.49
	OpenGlRenderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TConstruct-1.18.1-3.4.2.60.jar                    |Tinkers' Construct            |tconstruct                    |3.4.2.60            |DONE      |Manifest: NOSIGNATURE
		rsrequestify-2.2.0.jar                            |RSRequestify                  |rsrequestify                  |2.2.0               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		HostileNeuralNetworks-1.18.1-3.0.8.jar            |Hostile Neural Networks       |hostilenetworks               |3.0.8               |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.18.1-7.1.0-145.jar         |Immersive Engineering         |immersiveengineering          |1.18.1-7.1.0-145    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		EasyMagic-v3.2.1-1.18.1-Forge.jar                 |Easy Magic                    |easymagic                     |3.2.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.18.1-9.4.1.168.jar                          |Just Enough Items             |jei                           |9.4.1.168           |DONE      |Manifest: NOSIGNATURE
		wthit-forge-4.5.5.jar                             |wthit                         |wthit                         |4.5.5               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.1.jar                     |Flywheel                      |flywheel                      |1.18-0.6.1.63       |DONE      |Manifest: NOSIGNATURE
		alloyed-1.18.1-v1.2a.jar                          |Create: Alloyed               |alloyed                       |1.18.1              |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.2.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.2      |DONE      |Manifest: NOSIGNATURE
		Mantle-1.18.1-1.8.37.jar                          |Mantle                        |mantle                        |1.8.37              |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4f.jar                         |Create                        |create                        |0.4f                |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.1-6.1.1.jar                          |Placebo                       |placebo                       |6.1.1               |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.1-10.1.1.jar                  |Storage Drawers               |storagedrawers                |10.1.1              |DONE      |Manifest: NOSIGNATURE
		ToughAsNails-1.18.1-6.0.0.67-universal.jar        |Tough As Nails                |toughasnails                  |1.18.1-6.0.0.67     |DONE      |Manifest: NOSIGNATURE
		chromatocreeper-1.18.1-1.1.jar                    |§3Chromato Creeper§r          |chromatocreeper               |1.1                 |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.18-1.6.0.jar            |Better Third Person           |betterthirdperson             |1.6.0               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.1-3.15.15.550.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.1-3.15.15.550  |DONE      |Manifest: NOSIGNATURE
		BuddycardsExpansions-1.18.1-1.0.4.jar             |Buddycards Expansions         |buddycardsexp                 |1.18.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		Ore+Creeper-1.18.1-1.1.6.jar                      |Ore Creeper                   |ore_creeper                   |1.18.1-1.1.6        |DONE      |Manifest: NOSIGNATURE
		ClickMachine-1.18.1-6.0.2.jar                     |Click Machine                 |clickmachine                  |6.0.2               |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.2.1-1.18.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.2.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		hyperbox-1.18.1-2.0.0.0.jar                       |Hyperbox                      |hyperbox                      |2.0.0.0             |DONE      |Manifest: NOSIGNATURE
		PizzaCraft-1.18.1-5.0.0.jar                       |PizzaCraft                    |pizzacraft                    |5.0.0               |DONE      |Manifest: NOSIGNATURE
		randomium-1.18.1-1.9.jar                          |Randomium                     |randomium                     |1.18.1-1.9          |DONE      |Manifest: NOSIGNATURE
		mininggadgets-1.10.2.jar                          |Mining Gadgets                |mininggadgets                 |1.10.2              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.1.1-universal.jar                 |Forge                         |forge                         |39.1.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Aquaculture-1.18.1-2.3.3.jar                      |Aquaculture 2                 |aquaculture                   |1.18.1-2.3.3        |DONE      |Manifest: NOSIGNATURE
		infiniverse-1.18.1-1.0.0.1.jar                    |Infiniverse                   |infiniverse                   |1.0.0.1             |DONE      |Manifest: NOSIGNATURE
		EasyShulkerBoxes-v3.0.0-1.18.1-Forge.jar          |Easy Shulker Boxes            |easyshulkerboxes              |3.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Buddycards-1.18.1-3.0.6.jar                       |Buddycards Core               |buddycards                    |1.18.1-3.0.6        |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.10.1.jar                         |Refined Storage               |refinedstorage                |1.10.1              |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.8.1.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.1               |DONE      |Manifest: NOSIGNATURE
		TradingPost-v3.1.2-1.18.1-Forge.jar               |Trading Post                  |tradingpost                   |3.1.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		selene-1.18-1.13.2.jar                            |Selene                        |selene                        |1.18-1.13.2         |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.1-1.2.5.jar                  |Supplementaries               |supplementaries               |1.2.5               |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.18.1-2.1.49d-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.49d-1.18.1      |DONE      |Manifest: NOSIGNATURE
		createaddition-1.18.1-20220328a.jar               |Create Crafts & Additions     |createaddition                |1.18.1-20220328a    |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: e4db91fe-3688-4373-880f-5c79910a7d11
	FML: 39.1
	Forge: net.minecraftforge:39.1.1

**Comment by Commoble** [comment]
Thanks for finding this, should be fixed in 1.18.2-2.0.0.2
